config/routes.rb
Wftb::Application.routes.draw do
  devise_for :users

  resources :games do
    get "do_war_status", :on => :member
  end

  resources :games_players

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :creator, :class_name => "User", :foreign_key => "creator", :inverse_of => :created

  has_many :journal_items
  has_many :games_players
  has_many :users, :through => :games_players
  has_and_belongs_to_many :war_status_card_draws, :class_name => "WarStatusCard", :join_table => :games_war_status_draws

  attr_accessible :creator
  attr_accessible :name

  validates :creator, :presence => true
  validates :name, :presence => true
  validate :at_least_two_players

  before_create    :create_initial_log_message
  after_initialize :set_defaults

  # Games that user is a participant in, whether or not (s)he owns the game
  scope :participating, lambda { |user| joins(:games_players).where("games_players.user_id = ?", user.id) }

  def self.player_names ; %w/Albatros Fokker Halberstadt Pfalz/; end

  def find_player_by_side_name(side_name)
    games_players.each { |p| return p if p.side_name.upcase == side_name.upcase }
    nil
  end

  def albatros
    games_players.each { |p| return p if p.side_name == "Albatros" }
    nil
  end

  def fokker
    games_players.each { |p| return p if p.side_name == "Fokker" }
    nil
  end

  def halberstadt
    games_players.each { |p| return p if p.side_name == "Halberstadt" }
    nil
  end

  def pfalz
    games_players.each { |p| return p if p.side_name == "Pfalz" }
    nil
  end

  def albatros_email
    albatros && albatros.user.email
  end

  def fokker_email
    fokker && fokker.user.email;
  end

  def halberstadt_email
    halberstadt && halberstadt.user.email
  end

  def pfalz_email
    pfalz && pfalz.user.email;
  end

  def decide_winner
    max_score = games_players.inject(0) { |max,gp| [max, gp.bank + gp.score].max }
    games_players.each do |gp|
      if max_score == gp.bank + gp.score
        gp.winner = true
      end
    end
  end

  def is_game_over
    return true if self.german_morale <= 0
    return true if self.allied_morale <= 0
    return true if self.inflation     >= 10
    false
  end

  def check_all_orders_in!
    unless games_players.find { |gp| !gp.has_current_orders? }
      self.current_phase = "implement"
    end
  end

  # Journal items created since this instance in memory was created (whether new or from the db)
  def new_journal_items(timestamp)
    journal_items.where("created_at >= ?", timestamp).order("id ASC")
  end

  def execute_war_status_card(card)
    log "war_status", card.card_num, card.title

    if card.do_inflation
      self.inflation += 1
      log "inflation", self.inflation
      # TODO reduce player's Score
    end

    self.german_morale = [self.german_morale - card.german_morale_loss, 0].max
    log "german_morale", card.german_morale_loss, self.german_morale

    self.allied_morale = [self.allied_morale - card.allied_morale_loss, 0].max
    log "allied_morale", card.allied_morale_loss, self.allied_morale

    self.contracts_available += [card.new_contracts - self.contracts_left, 0].max
    log "new_contracts", self.contracts_available, card.new_contracts, self.contracts_left

    if card.do_reshuffle
      war_status_card_draws.clear
      war_status_card_draws << WarStatusCard.all
      log "reshuffle"
    end

    if card.upgraded_allied_ac
      if self.allied_power < max_player_power
        d6 = (1..6).to_a.sample
        old_allied_power = self.allied_power
        self.allied_power += d6
        log "allied_upgrade", self.allied_power, old_allied_power, max_player_power, d6
      else
        log "allied_no_upgrade", self.allied_power, max_player_power
      end

    elsif card.new_allied_ac
      d6 = (1..6).to_a.sample
      self.allied_power = self.allied_power + d6
      log "allied_new_ac", self.allied_power, d6

    elsif card.allied_technology_leap
      d6 = (1..6).to_a.sample
      old_allied_power = self.allied_power
      self.allied_power = [self.allied_power, max_player_power].max + (1..6).to_a.sample
      log "allied_leap", self.allied_power, old_allied_power, max_player_power, d6
    end

    # TODO power bonus to morale
    # TODO game over? (including extra inflation)
    # TODO mark winner
    self.complete = is_game_over

    # Archive the orders for future reference and reset them for the new turn
    games_players.each do |gp|
      gp.games_players_orders << GamesPlayersOrder.create(order1: gp.order1, order2: gp.order2, turn: self.turn)
      gp.order1 = gp.order2 = "None"
    end

    # It's next turn!
    unless self.complete
      self.turn += 1
      log "new_turn", self.turn
    end
  end

  # Parameter is for testing purposes
  def draw_war_status_card(card_num=nil)
    card = card_num ? war_status_card_draws.find { |c| c.card_num == card_num } : war_status_card_draws.sample
    war_status_card_draws.delete card
    card
  end

  def action_required?(user)
    case self.current_phase
    when "orders"
      games_players.detect { |gp| gp.user == user && !gp.has_current_orders? }

    else
      false
    end
  end

  def max_player_power
    games_players.inject(0) { |sum, player| sum += player.power }
  end

  def at_least_two_players
    errors.add(:base, "You must have at least two players") unless games_players.size >= 2
  end

  def set_defaults
    if new_record?
      self.allied_morale       = 25
      self.allied_power        = 4
      self.complete            = false
      self.contracts_available = 4 # TODO: should depend on number of players
      self.contracts_left      = 0
      # creator is filled in by controller
      self.current_phase       = "orders"
      self.games_players       = []
      self.german_morale       = 25
      self.inflation           = 0
      self.turn                = 1

      self.war_status_card_draws << WarStatusCard.all
    end
  end

  def create_initial_log_message
    log "init", albatros_email, fokker_email, halberstadt_email, pfalz_email
  end

  def log(item_type, arg1=nil, arg2=nil, arg3=nil, arg4=nil)
    ji = journal_items.build(item_type: item_type, turn: turn, arg1: arg1, arg2: arg2, arg3: arg3, arg4: arg4)
    ji.save
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, :except => :index

  # GET /games/:id/do_war_status(.:format)
  def do_war_status
    @now = DateTime.now
    @game = Game.find(params[:id])

    # only game owner can do war status
    if @game.creator != current_user
      # TODO
    end

    card = @game.draw_war_status_card()
    @game.execute_war_status_card(card)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: "War Status Card #{card.card_num}: #{card.title}" }
        format.json { render json: @game.new_journal_items(@now).to_json(:methods => :event_text) }
      end
    end
  end

  # GET /games
  # GET /games.json
  def index
    @my_created_games       = []
    @my_participating_games = []
    @other_games            = Game.all

    if current_user
      @my_created_games = current_user.created
      @my_participating_games = Game.participating(current_user) - @my_created_games
      @other_games -= @my_created_games
      @other_games -= @my_participating_games
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(:name => params[:game][:name])

    @game.update_attributes(:creator => current_user)
    assign_players(@game)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if assign_players(@game)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

private
  def assign_players(game)
    Game.player_names.each do |pname|

      # If side is now unassigned....
      if params[:game]["#{pname.downcase}_email"].empty?
        p = game.find_player_by_side_name(pname)
        # ...but it used to exist, we need to delete it
        game.games_players.delete(p) if p

      else # side is now assigned
        user = User.where("email = ?", params[:game]["#{pname.downcase}_email"]).first()
        # TODO: user.nil?

        p = game.find_player_by_side_name(pname)

        # if side wasn't already assigned for this game, just add it
        if p.nil?
          game.games_players.build(:user => user, :side_name => pname)

        else # but if side /does/ already exist, substitute the new email address
          p.user = user
          p.save
        end
      end
    end

    true
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= semantic_form_for(@game) do |f| 
  - if @game.errors.any? 
    #error_explanation
      %h2
        = pluralize(@game.errors.count, "error") 
        prohibited this game from being saved:

      %ul
      - @game.errors.full_messages.each do |msg| 
        %li
          = msg 

  = f.input :name, :label => "Game Name"

  = f.input :albatros_email, :as => :string, :label => "Albatros"
  
  = f.input :fokker_email, :as => :string, :label => "Fokker"
  
  = f.input :halberstadt_email, :as => :string, :label => "Halberstadt"

  = f.input :pfalz_email, :as => :string, :label => "Pfalz"

  = f.submit 

app/views/games/_summary.html.haml
-# Renders a single game in summary format, such as found on the index page
-# Local variables required: "game" (Game instance)

%tr
  %td.left
    = game.action_required?(current_user) ? "!" : ""

  %td.left
    = link_to game.name, game
  %td{ id: "turn" }
    = game.turn
  %td{ id: "german_morale" }
    = game.german_morale
  %td{ id: "allied_morale" }
    = game.allied_morale
  %td{ id: "allied_power" }
    = game.allied_power
  %td{ id: "inflation" }
    = "#{game.inflation * 10}%"
  %td{ id: "contracts_available" }
    = game.contracts_available

app/views/games/_summary_header.html.haml
-# Renders the header for the rows rendered by _summary.html.haml.
-# Local variables required: none

%tr
  %th
  %th
  %th
  %th.center{ :colspan => 2 } Morale
  %th Allied
  %th
  %th Contracts

%tr
  %th
  %th.left Game
  %th Turn
  %th German
  %th Allied
  %th Power
  %th Inflation
  %th Available

app/views/games/edit.html.haml
%h1 Editing game

= render 'form'

= link_to 'Show', @game
|
= link_to 'Back', games_path
|
= link_to 'Delete', @game, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete #{@game.name}"

app/views/games/index.html.haml
- content_for :title do
  WftB Online: Games List

- if user_signed_in?

  - if @my_created_games.size > 0

    %table.gameInfo
      %caption Games I'm Running
      = render "summary_header"

      - @my_created_games.each do |game|
        = render :partial => "summary", :locals => { :game => game, :current_user => current_user }

  - else

    None

  - if user_signed_in?
    %br
    = link_to 'Create New Game', new_game_path

  - if @my_participating_games.size > 0

    %table.gameInfo
      %caption Games I'm Playing
      = render "summary_header"

      - @my_participating_games.each do |game|
        = render :partial => "summary", :locals => { :game => game, :current_user => current_user }

%table.gameInfo
  %caption
    = user_signed_in? ? "Other Games" : "Current Games"

  - if @other_games.size > 0

    = render "summary_header"

    - @other_games.each do |game|
      = render :partial => "summary", :locals => { :game => game }

  - else

    %tr
      %td
        None

app/views/games/new.html.haml
%h1 New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%table.gameInfo
  = render "summary_header"
  = render :partial => "summary", :locals => { :game => @game }

%br

%table.gameInfo
  %tr
    %th.left Player
    %th Score
    %th Bank
    %th Power
    %th Factories
    %th.left Orders

  - Game.player_names.each do |side_name|
    - p = @game.find_player_by_side_name(side_name)
    - if p
      %tr
        %td.left{ id: (side_name + "_email") }
          = "#{side_name} (#{p.user.email})"

        %td{ id: (side_name + "_score") }
          = p.score

        %td{ id: (side_name + "_bank") }
          = p.bank

        %td{ id: (side_name + "_power") }
          = p.power

        %td{ id: (side_name + "_factories") }
          = p.factories

        %td.left{ id: (side_name + "_orders") }
          - o = current_orders_for_user(current_user, p)
          - if o.respond_to? :size  # it's an array
            = semantic_form_for p, { :html => { :class => "orders_form" } } do |f|
              = f.input :order1, :as => :select, :collection => GamesPlayersOrder.options,
                                                 :input_html => { :multiple => false },
                                                 :include_blank => false
              = f.input :order2, :as => :select, :collection => GamesPlayersOrder.options,
                                                 :input_html => { :multiple => false },
                                                 :include_blank => false
              = f.action :submit, :label => "Done"

          - elsif o
            Orders Entered

          - else
            No Orders Yet

%br

- if user_signed_in? && @game.creator == current_user
  = link_to "Execute War Status Phase", do_war_status_game_path, :remote => true, "data-type" => :json, :id => "execute_war_status_phase"

%br

= link_to "Edit", edit_game_path(@game)
|
= link_to "Back", games_path

%h3 Game Log

%table#journal_items
  - @game.journal_items.order("created_at DESC").each do |m|
    %tr
      %td
        = m.created_at
      %td
        = m.event_text